# Generated by Django 4.2.4 on 2023-08-03 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('edad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anio_edicion', models.IntegerField()),
                ('paginas', models.PositiveIntegerField()),
                ('idioma', models.CharField(max_length=20)),
                ('editorial', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaApp.autor')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='pais_nacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecaApp.pais'),
        ),
    ]
